#!/usr/bin/env bash

confirm() {
    # call with a prompt string or use a default
    read -r -p "${1:-Are you sure? [y/N]} " response
    if [[ "$response" =~ ^(yes|y)$ ]] ; then
	true
    else
	false
    fi
}

if [[ $# -ge 2 ]] && [[ "$1" == "reset" ]] && [[ "$2" == "--hard" ]] ; then
    ! confirm && exit 1
fi

/usr/bin/env git "$@"
