#!/bin/bash
# Note: standard awk, which comes as default in some GNU/Linux distributions,
# does not work here.
# Install gawk, e.g.:
# sudo apt install gawk

if ! awk --version | head -1 | grep "GNU Awk" >/dev/null 2>&1 ; then
    echo "GNU Awk required, install with e.g. `sudo apt install gawk`" ;
    exit 1
fi

display_usage() {
    echo "Usage:"
    echo "    $(basename $0) <tty> [bit rate]"
}

if [[ ( $@ == "--help") ||  $@ == "-h" ]]
then
   display_usage
   exit 0
fi

if [[ $# -lt 1 ]]; then
   display_usage
   exit 1
fi

tty=$1
shift

if [[ $# -gt 0 ]]; then
   bit_rate=$1
   stty -F $tty $bit_rate
fi

awk '{ print strftime("%Y-%m-%dT%H:%M:%S |"), $0; fflush(); }' $tty
