#!/bin/bash
echo "Undock" >> "$XMONAD_LOG_FILE"

if type monitor_laptop_set.sh ; then
    monitor_laptop_set.sh
    wallpaper_random_set.sh
fi

if type compton; then
    echo "Start compton if not running" >> "$XMONAD_LOG_FILE"
    # start compton if not running. xrandr seems to crash it sometimes.
    pgrep compton || compton --config "$HOME/.xmonad/compton.conf" &
fi

if type layout_dell.sh; then
    # Changing mode looks like it does something with X that breaks the layout
    layout_dell.sh
fi

#### !!! Here is a gotcha. After starting a gnome session, starting
#### xfce4-power-manager hangs at next start of xmonad. With this
#### commented out, xmonad does starts, AND does have a power icon. It
#### seems like the gnome power manager took over, upon starting the
#### gnome DE, and borked xfce4-power-manager?
####if type xfce4-power-manager; then
####    xfce4-power-manager
####fi

echo "undock finished" >> "$XMONAD_LOG_FILE"
